@startuml lomap_deployment
actor User
node Device {
    component Browser
}
node WebServer {
    node Docker {
        component WebApp
        component RestAPI
    }
}

node Mapbox
node PodProvider {
    database User_Pod
}
User->Device

Device<-->WebServer:https
WebApp<-->PodProvider:https
WebApp<--Mapbox:https
Device<->RestAPI:https
@enduml